# Generated by Django 5.2 on 2025-05-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpms',
            name='xml_file',
        ),
        migrations.AddField(
            model_name='bpms',
            name='xml_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
